seed: 42
train:
    epochs: 100
    max_lr: 0.05
    lr_schedule: "linear"
    momentum: 0.9
    batch_size: 128
    optimizer: "sgd"
num_log_steps: 100
label_idx: 10
linearize: False
data:
  shape: [32, 32, 1]
  epsilon: 1
  sigma: 1
  num_train: 10000
  num_test: 10000

# Support for config groups
defaults:
    - model: lenet
